openapi: 3.0.1
info:
  title: mocktarget1
  description: ''
  version: '1.0'
servers:
  - url: https://azure-apim-01.azure-api.net/mocktarget1
paths:
  /:
    get:
      summary: all
      description: all
      operationId: all
      responses:
        '200':
          description: ''
  /json:
    get:
      summary: json
      description: json
      operationId: json
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]